export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  HANDOVER_CONSOLE_LOCKED: "HANDOVER_CONSOLE_LOCKED",
  HANDOVER_NOT_ACTIVE: "HANDOVER_NOT_ACTIVE",
  HANDOVER_NOT_STANDBY: "HANDOVER_NOT_STANDBY",
  HANDOVER_BATCH_MISMATCH: "HANDOVER_BATCH_MISMATCH"
} as const;
